### ISSUE TITLE
[BUG]: bsl-types-fixed-width-ints

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/llvm-project#23]
This doesn't seem to be working with headers. It found issues with .cpp files, but it doesn't seem to be seeing issues with headers.

**Comment by rianquinn** [comment]
Specifically, it didn't find an issue with bsl::cstr_type

**Comment by cjams** [comment]
Fixed in https://github.com/Bareflank/llvm-project/pull/36/commits/d728dd2c33608e848642bd68ec6a5cda4e634ab9
